user:
  full_name: "John Doe"
  age: "28"
  gender: "Male"
  ethnicity: "White"
  height: "6 foot 2 inches"
  weight: "195lbs"
  hair_color: "Brown"
  eye_color: "Brown"
  medical_conditions: "None"
  medications: "None"

user_vehicle:
  color: "White"
  year: "2020"
  make: "Honda"
  model: "Civic"
  license_plate_number: "1ABC234"

# Run "Time.now.strftime('%:z')" in IRB to get this string.
time_zone_offset: "-08:00"